name: C/C++ CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-jammy

    steps:
    - uses: actions/checkout@v4
    - name: bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure
    - name: make SpinningCube
      working-directory: HAHAFUN/SpinningCube
      run: |
       sudo apt-get -y install libglew-dev mesa-utils
       make all
    - name: make cube1
      working-directory: HAHAFUN/cube1
      run: |
       make
    # - name: make freeglut
    #   working-directory: HAHAFUN/freeglut
    #   run: |
    #    sudo apt-get -y install freeglut3 freeglut3-dev libglew-dev mesa-utils
    #    make all
